# -*- coding: utf-8 -*-
"""Rose's_Workbook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17rZAhoj6V9EQxAFUpuE5D_XtuRdSJObd
"""

get_ipython().system('pip install onnxruntime')
get_ipython().system('pip install -U ultralytics av')
get_ipython().system('pip install opencv-python')
get_ipython().system('pip install -U transformers')
get_ipython().system('pip install segment_anything')
from transformers import Sam3Processor, Sam3Model
from google.colab import drive
drive.mount('/content/drive')

from huggingface_hub import login

login(token="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") # <--- Replace this with your actual token

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("mask-generation", model="facebook/sam3")

# Load model directly
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("facebook/sam3")
model = AutoModel.from_pretrained("facebook/sam3")

import cv2
import numpy as np
import torch
from ultralytics import YOLO
from PIL import Image

# -------------------------
# Load Models
# -------------------------

det_model = YOLO("/content/drive/MyDrive/best.onnx")

# pipe = your existing SAM3 transformers pipeline
# (already loaded earlier)

# -------------------------
# Video Setup
# -------------------------

cap = cv2.VideoCapture("/content/drive/MyDrive/output2.mp4")

width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)

out = cv2.VideoWriter(
    "segmented_output.mp4",
    cv2.VideoWriter_fourcc(*"mp4v"),
    fps,
    (width, height)
)

# -------------------------
# Processing Loop
# -------------------------

while cap.isOpened():

    ret, frame = cap.read()

    if not ret:
        break

    overlay = frame.copy()

    # -------------------------
    # YOLO Detection
    # -------------------------

    results = det_model(frame)[0]

    boxes = results.boxes.xyxy.cpu().numpy()

    sam_boxes = []

    for x1, y1, x2, y2 in boxes:

        # Filter very small detections
        area = (x2 - x1) * (y2 - y1)

        if area < 800:
            continue

        sam_boxes.append([x1, y1, x2, y2])

    if len(sam_boxes) == 0:
        out.write(frame)
        continue

    # -------------------------
    # Convert Frame for SAM
    # -------------------------

    pil_image = Image.fromarray(
        cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    )

    # -------------------------
    # Run SAM ONCE for all boxes
    # -------------------------

    with torch.inference_mode():

        sam_results = pipe(
            image=pil_image,
            bboxes=[sam_boxes]
        )

    # -------------------------
    # Overlay Masks
    # -------------------------

    alpha = 0.5

    for mask_tensor in sam_results["masks"]:

        mask = mask_tensor.cpu().numpy() > 0

        if mask.ndim == 3:
            mask = mask.squeeze()

        overlay[mask] = (
            overlay[mask] * (1 - alpha)
            + np.array([0, 255, 0]) * alpha
        ).astype(np.uint8)

    # -------------------------
    # Save Frame
    # -------------------------

    out.write(overlay)

cap.release()
out.release()