# -*- coding: utf-8 -*-
"""trial4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDbXO3sHx0h7OwtYdbSOxD2miuGM-1lw
"""

get_ipython().system('pip install onnxruntime')
get_ipython().system('pip install -U ultralytics av')
get_ipython().system('pip install opencv-python')
get_ipython().system('pip install -U transformers')
get_ipython().system('pip install segment_anything')

from transformers import Sam3Processor, Sam3Model
from google.colab import drive
drive.mount('/content/drive')

pip install git+https://github.com/facebookresearch/segment-anything-2.git

!wget https://dl.fbaipublicfiles.com/segment_anything/sam3_hiera_large.pt

!wget https://raw.githubusercontent.com/facebookresearch/segment-anything-2/main/sam2/configs/sam2_hiera_l.yaml

!ls

!wget -O sam2_hiera_large.pt https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_large.pt

import torch
from sam2.build_sam import build_sam2
from sam2.sam2_image_predictor import SAM2ImagePredictor

device = "cuda" if torch.cuda.is_available() else "cpu"

model = build_sam2("sam2_hiera_l.yaml", "sam2_hiera_large.pt", device=device)
predictor = SAM2ImagePredictor(model)

!ffmpeg -i "/content/drive/MyDrive/row3_converted_edit.MP4-.ts" -c:v libx264 -c:a aac row3_fixed.mp4

import cv2

cap = cv2.VideoCapture("row3_fixed.mp4")
print("Opened:", cap.isOpened())
print("Frames:", int(cap.get(cv2.CAP_PROP_FRAME_COUNT)))

import cv2
import numpy as np
import torch
from ultralytics import YOLO

# YOLO detection model
det_model = YOLO("/content/drive/MyDrive/best.onnx", task="detect")

cap = cv2.VideoCapture("row3_fixed.mp4")

width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)

out = cv2.VideoWriter(
    "segmented_output3.mp4",
    cv2.VideoWriter_fourcc(*"mp4v"),
    fps,
    (width, height)
)

frame_count = 0

while cap.isOpened():

    ret, frame = cap.read()
    if not ret:
        break

    frame_count += 1
    print("Processing frame:", frame_count)

    # YOLO detection
    results = det_model(frame)[0]
    boxes = results.boxes.xyxy.cpu().numpy()

    overlay = frame.copy()
    alpha = 0.5

    # IMPORTANT: set image once per frame
    predictor.set_image(frame)

    if len(boxes) > 0:

        masks, scores, logits = predictor.predict(
            box=boxes,
            multimask_output=False
        )

        for mask, box in zip(masks, boxes):

            mask = mask.squeeze() > 0

            color = np.random.randint(0,255,(3,),dtype=int)

            overlay[mask] = (
                overlay[mask] * (1 - alpha) + color * alpha
            ).astype(np.uint8)

            x1,y1,x2,y2 = box.astype(int)
            cv2.rectangle(overlay,(x1,y1),(x2,y2),(0,255,0),2)

    out.write(overlay)

cap.release()
out.release()



import cv2
import numpy as np
import torch
from ultralytics import YOLO

# YOLO detection model
det_model = YOLO("/content/drive/MyDrive/best.onnx", task="detect")

cap = cv2.VideoCapture("/content/drive/MyDrive/row1_converted.mp4")

width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)

out = cv2.VideoWriter(
    "segmented_output_t5.mp4",
    cv2.VideoWriter_fourcc(*"mp4v"),
    fps,
    (width, height)
)

frame_count = 0

while cap.isOpened():

    ret, frame = cap.read()
    if not ret:
        break

    frame_count += 1
    print("Processing frame:", frame_count)

    # YOLO detection
    results = det_model(frame)[0]
    boxes = results.boxes.xyxy.cpu().numpy()

    overlay = frame.copy()
    alpha = 0.5

    # IMPORTANT: set image once per frame
    predictor.set_image(frame)

    if len(boxes) > 0:

        masks, scores, logits = predictor.predict(
            box=boxes,
            multimask_output=False
        )

        for mask, box in zip(masks, boxes):

            mask = mask.squeeze() > 0

            color = np.random.randint(0,255,(3,),dtype=int)

            overlay[mask] = (
                overlay[mask] * (1 - alpha) + color * alpha
            ).astype(np.uint8)

            x1,y1,x2,y2 = box.astype(int)
            cv2.rectangle(overlay,(x1,y1),(x2,y2),(0,255,0),2)

    out.write(overlay)

cap.release()
out.release()